name: docker
on:
  schedule:
    - cron: '0 1 * * 1'  # Every Monday at 1am
  push:
    branches:
      - "main"
      - "development"
    tags:
      - "*"
permissions: read-all

jobs:
  build:
    name: Build app (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { arch: linux/amd64, os: ubuntu-latest }
          - { arch: linux/arm64, os: ubuntu-24.04-arm }

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event_name == 'schedule' && 'main' || github.ref }}

      - name: Build image
        uses: unil-lettres/actions/docker-build@main
        with:
          dockerfile: ./Dockerfile
          platform: ${{ matrix.arch }}
          image_repository: ${{ vars.DOCKERHUB_REPOSITORY }}
          name_prefix: http
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  merge-prod:
    name: Merge Prod
    runs-on: ubuntu-latest
    needs: [build]
    if: success() && (github.event_name == 'schedule' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))

    steps:
      - uses: actions/checkout@v5
        with:
          ref: main

      - name: Merge service
        uses: 'unil-lettres/actions/docker-merge-prod@main'
        with:
          image_repository: ${{ vars.DOCKERHUB_REPOSITORY }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  merge-app-dev:
    name: Merge app Dev
    runs-on: ubuntu-latest
    needs: [build]
    if: success() && github.event_name != 'schedule' && github.ref == 'refs/heads/development'

    steps:
      - uses: actions/checkout@v5
        with:
          ref: development

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-http-*
          merge-multiple: true

      - name: Merge digests into manifest
        uses: 'unil-lettres/actions/docker-merge@main'
        with:
          image_repository: ${{ vars.DOCKERHUB_REPOSITORY }}
          tag: dev-latest
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  update-description:
    name: Update Description
    runs-on: ubuntu-latest
    needs: [merge-prod] # Update description only for production

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: main

      - name: Update description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.DOCKERHUB_REPOSITORY }}
